---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  generation: 1
  labels:
    app: mysql-backup
    redeployment-enabled: "true"
    redeployment-lifecycle: around-database
    redeployment-start: "true"
    redeployment-stop: "true"
  name: mysql-backup-persistent
spec:
  replicas: 1
  selector:
    app: mysql-backup
  strategy:
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: mysql-backup
        redeployment-enabled: "true"
        redeployment-lifecycle: around-database
        redeployment-start: "true"
        redeployment-stop: "true"
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: database-credentials
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: database-credentials
        - name: MYSQL_SERVICE_HOST
          value: mysql
        - name: MYSQL_DATABASE
          value: database
        - name: BACKUP_DATA_DIR
          value: /opt/app-root/backup/
        - name: BACKUP_KEEP
          value: "5"
        - name: BACKUP_MINUTE
          value: "10"
        - name: BACKUP_HOUR
          value: 11,19
        image: appuio/mysql-simple-backup-container
        imagePullPolicy: Always
        name: mysql-backup
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /opt/app-root/backup/
          name: mysql-backup-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysql-backup-data
        persistentVolumeClaim:
          claimName: mysql-backup
  test: false
  triggers:
  - type: ConfigChange
status: {}

