---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  generation: 1
  labels:
    app: mysql
    promotion-enabled: "true"
    redeployment-enabled: "true"
    redeployment-lifecycle: database
    redeployment-start: "true"
    redeployment-stop: "true"
  name: mysql
spec:
  replicas: 1
  selector:
    name: mysql
  strategy:
    recreateParams:
      timeoutSeconds: 600
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: mysql-persistent
        name: mysql
        promotion-enabled: "true"
        redeployment-enabled: "true"
        redeployment-lifecycle: database
        redeployment-start: "true"
        redeployment-stop: "true"
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: database-credentials
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: database-credentials
        - name: MYSQL_DATABASE
          value: database
        - name: MYSQL_KEY_BUFFER_SIZE
          value: 16M
        - name: MYSQL_SORT_BUFFER_SIZE
          value: 2M
        - name: MYSQL_INNODB_LOG_FILE_SIZE
          value: 128M
        - name: MYSQL_INNODB_LOG_BUFFER_SIZE
          value: 128M
        image: centos/mysql-56-centos7
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: mysql-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-database
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - mysql
      from:
        kind: ImageStreamTag
        name: mysql:5.7
        namespace: openshift
    type: ImageChange
  - type: ConfigChange
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
    template: mysql-persistent-template
  name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

