---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: rails
  name: rails
spec:
  host: your-public-hostname.example.com
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rails
status: {}
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: rails
  name: rails-alternate
spec:
  host: your-hostname.alternate.example.com
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rails
status: {}

