---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: maintenance-rails-storage-rsync
  name: maintenance-rails-storage-rsync
spec:
  replicas: 0
  selector:
    name: maintenance-rails-storage-rsync
  template:
    metadata:
      labels:
        app: maintenance-rails-storage-rsync
        name: maintenance-rails-storage-rsync
    spec:
      containers:
      - command:
        - tail
        - -f
        - /etc/hosts
        image: 172.30.1.1:5000/hitobito-templatersync-client
        imagePullPolicy: Always
        name: maintenance-rails-storage-rsync
        volumeMounts:
        - mountPath: /data/uploads
          name: useruploads
      volumes:
      - name: useruploads
        persistentVolumeClaim:
          claimName: useruploads
  triggers: []
status: {}

